app_id = "app_01j2f0dkp2ftsav0a29mgebv6q"

# This is where 'xtp plugin push' expects to find the wasm file after the build script has run.
bin = "dist/plugin.wasm"
extension_point_id = "ext_01j2f0wnyafykrdc6ve51jp0ac"
name = "tz"

[scripts]

  # xtp plugin build runs this script to generate the wasm file
  build = "mkdir -p dist && tinygo build -target wasi -o dist/plugin.wasm ."

  # xtp plugin init runs this script to format the plugin code
  format = "go fmt"

  # xtp plugin init runs this script before running the format script
  prepare = "go get ./..."
